/* Guard 50: ship obfuscated, self-verifying client code.
 *
 * Packs src/antidebug.src.js into antidebug.js and records its hash in
 * integrity.json, which the server serves so the page can verify it is running
 * the code that was actually published.
 *
 * HONESTY NOTE: this is *packing* — base64 + chunk shuffling + a string table —
 * not commercial-grade protection. Real products (Kasada, DataDome) use
 * control-flow flattening, opaque predicates, per-session generated VMs, and
 * rotate the whole bundle continuously. This raises the cost of a casual look;
 * it will not stop a determined analyst, and nothing that runs in the client
 * ever can.
 *
 * Usage: node tools/obfuscate.js
 */
"use strict";
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const ROOT = path.dirname(__dirname);
const SRC = path.join(ROOT, "src", "antidebug.src.js");
const OUT = path.join(ROOT, "antidebug.js");
const MANIFEST = path.join(ROOT, "integrity.json");

const source = fs.readFileSync(SRC, "utf8");

/* 1. Pack the payload as base64 and cut it into chunks. */
const b64 = Buffer.from(source, "utf8").toString("base64");
const CHUNK = 48;
const chunks = [];
for (let i = 0; i < b64.length; i += CHUNK) chunks.push(b64.slice(i, i + CHUNK));

/* 2. Shuffle the chunks deterministically and emit the reordering map, so the
 *    literal array in the output is not readable in source order. */
const order = chunks.map((_, i) => i);
for (let i = order.length - 1; i > 0; i--) {
  // Deterministic swap (no Math.random — the build must be reproducible).
  const j = crypto.createHash("sha256").update(`sg-shuffle-${i}`).digest()[0] % (i + 1);
  [order[i], order[j]] = [order[j], order[i]];
}
const shuffled = order.map((idx) => chunks[idx]);
const inverse = new Array(order.length);
order.forEach((originalIdx, position) => { inverse[originalIdx] = position; });

/* 3. Emit a loader that reassembles and executes the payload. */
const out = `/* GENERATED by tools/obfuscate.js — do not edit.
   Source of truth: src/antidebug.src.js  (guard 49)
   This file demonstrates guard 50 (obfuscated + integrity-checked delivery). */
(function(_0x1,_0x2){var _0x3=[],_0x4=0;for(;_0x4<_0x2.length;_0x4++){_0x3[_0x4]=_0x1[_0x2[_0x4]];}
var _0x5=_0x3.join('');var _0x6=(typeof atob==='function')?atob(_0x5):Buffer.from(_0x5,'base64').toString('binary');
var _0x7=decodeURIComponent(escape(_0x6));(0,eval)(_0x7);})(
${JSON.stringify(shuffled)},
${JSON.stringify(inverse)});
`;

fs.writeFileSync(OUT, out);

const hash = crypto.createHash("sha256").update(fs.readFileSync(OUT)).digest("hex");
fs.writeFileSync(MANIFEST, JSON.stringify({
  "antidebug.js": { sha256: hash, bytes: Buffer.byteLength(out) },
  generatedFrom: "src/antidebug.src.js",
  note: "Packing only — see the honesty note in tools/obfuscate.js",
}, null, 2) + "\n");

// Sanity: the packed output must still parse and be executable.
new Function(out); // throws on syntax error

console.log(`wrote ${OUT} (${Buffer.byteLength(out)} bytes, ${chunks.length} chunks)`);
console.log(`wrote ${MANIFEST}  sha256=${hash.slice(0, 16)}…`);
